pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch:'main',url:'https://github.com/skykesavanke/Backend_Deployment.git'
            }
        }
       

        stage('Deploy to Kubernetes') {
            steps {
                script {
                    
                    bat 'aws eks update-kubeconfig --region us-east-1 --name springapp-cluster'

                   
                    bat 'kubectl version --client'

                   
                    bat 'kubectl apply -f ./deployment/deployment.yaml'

                  
                    bat 'kubectl apply -f ./deployment/service.yaml'

                    bat 'kubectl get services'
                }
            }
        }
    }
}
