apiVersion: v1
kind: Service
metadata:
  name: springboot-deployment
spec:
  selector:
    app: springboot-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
